Adding altcoin + BTC totals
cryptoeax/arbbot pull request #56
Opened 2017-12-29 04:49 UTC by moinnadeem

Hey man! 

Here's the first PR that adds it to the UI elements. Working on the graph now.

Thanks!

2017-12-29 19:41 UTC, cryptoeax requested changes
Thanks a lot, looks great overall.  👍   I have a few small comments below which should be easy to address before this is ready to merge.

2017-12-29 19:41 UTC, cryptoeax commented on web/WebDB.php
> +        $wallets[ $coin ][ $exid ][ 'change_BTC' ] = floatval( ($balance  - self::getHistoricBalance( $coin, $exid)));
The `change_BTC` stuff doesn't make sense really, let me explain.  As the bot watches the market, it computes a desired balance for each altcoin currency, which means the amount of altcoins it wants to hold.  The "change_foo" fields for the altcoins denote the changes in this value.

As you can see, aggregating this value across all altcoin values doesn't really make a whole lot of sense, so let's remove the `change_BTC` parts and keep the `balanace_BTC` parts?

2017-12-29 19:41 UTC, cryptoeax commented on web/ui.js
> +                        if (xid in altcoinTotals) {
Once you address the previous comment, this part can be simplified...  This won't need to be an array any more.

2017-12-29 19:41 UTC, cryptoeax commented on web/ui.js
> +                    htmlData += "<a href=\"#\" coin=\"alt_btc\" exchange=\"" + xid + "\" mode=\"0\" class=\"showGraph\" title=\"Total balance (BTC + Altcoins)\">";
Can you please avoid making these links in this PR, since on its own, when this PR gets merged, clicking on these links won't do anything?

2017-12-29 19:41 UTC, cryptoeax commented on web/ui.js
> +                    Strats: For each coin, add XID to totals DB
Typo?

2017-12-29 19:41 UTC, cryptoeax commented on web/ui.js
> +                console.log(altcoinTotals);
Please remove the console.log...

2017-12-29 23:22 UTC, moinnadeem commented
Awesome! Thanks for getting back to me so quickly, I should be able to work on these tomorrow!

2017-12-30 06:45 UTC, cryptoeax commented
Fantastic! 👍  Thank you very much.

2018-01-01 23:30 UTC, moinnadeem commented
@cryptoeax This should address your concerns; please let me know if they don't!

2018-01-02 17:53 UTC, cryptoeax commented
I think they do, thanks very much!

2018-01-02 17:53 UTC, cryptoeax approved these changes

2018-01-02 17:53 UTC, merged

2018-01-02 17:59 UTC, cryptoeax commented
Note: I landed a follow-up for this PR to remove the trade and opportunity counts since they're just repeated from the Total section right below: 9cfb9d91b1715fe6385cd9b42b0baefccb1c052c